package com.hu.oneclick.dao;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.extension.conditions.query.LambdaQueryChainWrapper;
import com.hu.oneclick.model.annotation.Page;
import com.hu.oneclick.model.entity.TestCycle;
import com.hu.oneclick.model.domain.dto.LeftJoinDto;
import org.apache.ibatis.annotations.Param;
import java.util.List;
import java.util.Map;
